# Generated by Django 4.0.6 on 2022-07-15 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=1024, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=1024, verbose_name="Last name"),
                ),
                (
                    "address1",
                    models.CharField(max_length=1024, verbose_name="Address line 1"),
                ),
                (
                    "address2",
                    models.CharField(max_length=1024, verbose_name="Address line 2"),
                ),
                ("city", models.CharField(max_length=1024, verbose_name="City")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Zip code"
                    ),
                ),
                ("country", models.CharField(max_length=1024, verbose_name="Country")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
